"""empty message

Revision ID: 5ae6dd727326
Revises: 947ee1a9de7e
Create Date: 2021-12-08 15:05:24.573331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ae6dd727326'
down_revision = '947ee1a9de7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('association', sa.Column('jmeno', sa.String(length=250), nullable=True))
    op.add_column('association', sa.Column('email', sa.String(length=250), nullable=True))
    op.add_column('association', sa.Column('telefon', sa.String(length=250), nullable=True))
    op.add_column('association', sa.Column('popisek_dne', sa.String(length=250), nullable=True))
    op.drop_column('dates', 'popisek_dne')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dates', sa.Column('popisek_dne', sa.VARCHAR(length=250), nullable=True))
    op.drop_column('association', 'popisek_dne')
    op.drop_column('association', 'telefon')
    op.drop_column('association', 'email')
    op.drop_column('association', 'jmeno')
    # ### end Alembic commands ###
