"""empty message

Revision ID: 7b6aa9c1189d
Revises: 
Create Date: 2021-12-08 10:32:08.799911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b6aa9c1189d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dates', sa.Column('popisek_dne', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dates', 'popisek_dne')
    # ### end Alembic commands ###
