"""Initial migration.

Revision ID: 947ee1a9de7e
Revises: 7b6aa9c1189d
Create Date: 2021-12-08 15:03:10.417176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '947ee1a9de7e'
down_revision = '7b6aa9c1189d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('association', sa.Column('jmeno', sa.String(length=250), nullable=False))
    op.add_column('association', sa.Column('email', sa.String(length=250), nullable=False))
    op.add_column('association', sa.Column('telefon', sa.String(length=250), nullable=False))
    op.add_column('association', sa.Column('popisek_dne', sa.String(length=250), nullable=False))
    op.drop_column('dates', 'popisek_dne')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dates', sa.Column('popisek_dne', sa.VARCHAR(length=250), nullable=True))
    op.drop_column('association', 'popisek_dne')
    op.drop_column('association', 'telefon')
    op.drop_column('association', 'email')
    op.drop_column('association', 'jmeno')
    # ### end Alembic commands ###
